baseurl      = "/"
title        = "Jacob Shin"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"
staticDir = "static"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[params]
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
gitUrl = "https://github.com/jshin313/site/commit/"

# Subtitle for home
# homeSubtitle = "Projects, posts, notes, etc"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Metadata mostly used in document's head
description = "My homepage"
keywords = "homepage, blog"
images = [""]

# Default theme "light" or "dark"
defaultTheme = "dark"

enableThemeToggle = true

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[[params.social]]
name = "email"
url  = "mailto:jacobshin313@gmail.com"

[[params.social]]
name = "github"
url  = "https://github.com/jshin313"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/jacob-shin"

[languages]
[languages.en]
title = "Jacob Shin"
subtitle = "Notes, Posts, Projects, etc."
keywords = ""
copyright = 'Jacob Shin'
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = " "
logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
identifier = "CV"
name       = "CV"
url        = "/cv"
weight     = -102

[[menu.main]]
identifier = "notes"
name       = "Notes"
url        = "/notes"
weight     = -101

[[menu.main]]
identifier = "posts"
name       = "Posts"
url        = "/posts"
weight     = -100


[[menu.main]]
identifier = "about"
name       = "About"
url        = "/about"
weight     = -99



[markup]
[markup.highlight]
codeFences = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
hardWraps = true

